Upgrade firecracker-containerd binaries with v0.24 version of Firecracker
ease-lab/vhive pull request #227
Opened 2021-05-03 19:02 UTC by plamenmpetrov

Signed-off-by: Plamen Petrov <plamb0brt@gmail.com>

2021-05-28 21:28 UTC, ustiugov requested changes
LGTM but let's pull the latest changes for firecracker-containerd. particularly, we are interested in containerd 1.5

2021-05-29 15:00 UTC, ustiugov reviewed
do we have to fix the grpc version? why?

2021-06-18 06:55 UTC, plamenmpetrov commented on go.mod
> +	// Pin gPRC-related dependencies as like containerd v1.5.1
Might be. Do you want to fix it?

2021-06-18 07:14 UTC, plamenmpetrov commented on go.mod
>  	github.com/firecracker-microvm/firecracker-go-sdk => github.com/ease-lab/firecracker-go-sdk v0.20.1-0.20200625102438-8edf287b0123
This dependency is no longer required.

2021-06-18 07:19 UTC, ustiugov commented on go.mod
> +	// Pin gPRC-related dependencies as like containerd v1.5.1
Yes please

2021-06-18 07:20 UTC, ustiugov commented
Rebase when ready and let's merge it

2021-06-18 07:22 UTC, plamenmpetrov commented on scripts/clean_fcctr.sh
> +    /run/containerd/s
Not incomplete. This deletes any remaining shim sockets from containerd. https://github.com/containerd/containerd/blob/36cc874494a56a253cd181a1a685b44b58a2e34a/runtime/v2/shim/util_unix.go#L74

I remember having an issue where the shim socket was not cleaned up.

2021-06-18 07:23 UTC, plamenmpetrov commented on ctriface/go.mod
> +	// Pin gPRC-related dependencies as like containerd v1.5.1
I copied this replace block from firecracker-containerd.

2021-06-18 08:16 UTC, ustiugov commented on go.mod
>  	github.com/firecracker-microvm/firecracker-go-sdk => github.com/ease-lab/firecracker-go-sdk v0.20.1-0.20200625102438-8edf287b0123
then need to remove it

2021-06-18 08:25 UTC, ustiugov commented
please add a note to CHANGELOG.md in the Changed section of unreleased

2021-06-18 21:10 UTC, ustiugov approved these changes

2021-06-18 21:10 UTC, merged