Bump Knative to v0.23.0
ease-lab/vhive pull request #264
Opened 2021-06-01 14:13 UTC by boramalper

Signed-off-by: Bora M. Alper <bora@boramalper.org>

2021-06-01 14:14 UTC, boramalper commented
**Does NOT Work Yet!**

Using [ease-lab/serving@v0.23_vhive](https://github.com/ease-lab/serving/tree/v0.23_vhive), I have tried to update Knative for vHive to v0.23.0 ([the instructions](https://github.com/ease-lab/vhive/wiki/TMP:-How-to-Update-Knative-for-vHive)).

When I set up a vHive single-node stock-only Knative node (using the new YAML files that I have generated, see [boramalper/vhive@v0.23_vhive](https://github.com/boramalper/vhive/tree/v0.23_vhive) and [`generate-yamls.sh` logs](https://gist.github.com/boramalper/660b005842e00a7f4d96421dc13f52bc)), I still get Knative v0.21.0 installed:

```bash
$ kubectl get namespace knative-serving -o 'go-template={{index .metadata.labels "serving.knative.dev/release"}}'
v0.21.0
$ kubectl get namespace keventing -o 'go-template={{index .metadata.labels "eventing.knative.dev/release"}}'}}'
v0.21.0
$ kn version
Version:      v20210601-local-3cc608f
Build Date:   2021-06-01 13:32:05
Git Revision: 3cc608f
Supported APIs:
* Serving
  - serving.knative.dev/v1 (knative-serving v0.23.0)
* Eventing
  - sources.knative.dev/v1 (knative-eventing v0.23.0)
  - eventing.knative.dev/v1 (knative-eventing v0.23.0)
```

2021-06-01 16:20 UTC, boramalper commented
I have found that there is a mismatch between the tags of images published and the configuration files generated by `generate-yamls.sh`:

**`./configs/knative_yamls/serving-hpa.yaml`**:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoscaler-hpa
  namespace: knative-serving
  labels:
    serving.knative.dev/release: devel
    autoscaling.knative.dev/autoscaler-provider: hpa
spec:
  # [...]
  template:
    spec:
      # [...]
      containers:
        - name: autoscaler-hpa
          # This is the Go import path for the binary that is containerized
          # and substituted here.
          image: docker.io/vhiveease/autoscaler-hpa-85c0b68178743d74ff7f663a72802ceb:ad1052f88caa83f05335d2d7cd56ca3598991387986351727281715bf785f4c6
```

whereas the published image has been tagged `latest`:

![image](https://user-images.githubusercontent.com/5618038/120357421-19846e80-c30e-11eb-93f3-533401379256.png)

Investigating why tagging goes wrong, and how to fix it or do it correctly in the first place.

2021-06-01 17:25 UTC, shyamjesal commented
`latest` is a pseudo tag. The uploaded images do have their own tag apart from latest. Try finding that and then compare.

2021-06-02 11:52 UTC, boramalper commented
I tried twice (and yet another time with @MBaczun) today and all worked fine---Michal experienced some bugs with their Knative setup that I could not replicate and believe are transient.

I believe that the issues I experienced yesterday was due to using the wrong repo & branch...

Would any of you (@shyamjesal or @ustiugov) be able to try setting it up yourselves and confirm that it works? I am confident that it does, but would appreciate a third confirmation if possible.

## Testing Stock Knative Images
```bash
git clone --branch=v0.23_vhive https://github.com/boramalper/vhive
cd vhive
./scripts/cloudlab/setup_node.sh stock-only
sudo containerd  # in the background
./scripts/cluster/create_one_node_cluster.sh stock-only
# wait for the containers to boot up using 
watch kubectl get pods -A
```

**[Checking the version of your Knative components](https://knative.dev/docs/install/check-install-version/):**
```bash
kubectl get namespace knative-serving -o 'go-template={{index .metadata.labels "serving.knative.dev/release"}}'
kubectl get namespace knative-eventing -o 'go-template={{index .metadata.labels "eventing.knative.dev/release"}}'
```
Both shall return `v0.23.0`.

2021-06-02 12:17 UTC, ustiugov commented
thanks! we have the CI for that :) 

Can you please push your branch to the upstream repo and run the "Nightly integration tests" on that branch. if tests fail, I'll take a closer look

2021-06-02 12:29 UTC, ustiugov requested changes
Minor things (and hope the CRI tests would pass)

- [ ] need a simple fix in the CRI tests in the `cri` folder
- [ ] add a line to the Changelog, we gonna do 1.3 vHive release next week

2021-06-02 12:29 UTC, ustiugov commented on configs/knative_yamls/serving-default-domain.yaml
> +          args: ["-magic-dns=sslip.io"]
need to replace `xip.io` in the CRI tests (grep in the `cri/` folder) with sslip.io

2021-06-03 09:35 UTC, ustiugov submitted a review, later dismissed

2021-06-03 09:49 UTC, ustiugov submitted a review, later dismissed

2021-06-03 10:41 UTC, ustiugov commented
@shyamjesal can you please take a look at the artifact? Bora can troubleshoot with some of your guidance
https://github.com/ease-lab/vhive/actions/runs/902388125

2021-06-07 10:20 UTC, boramalper commented
Based on https://github.com/ease-lab/serving/pull/5.

vHive Nightly Integration Tests results: https://github.com/ease-lab/vhive/actions/runs/914303428

Only [CRI tests (nightly) (-dbg -snapshots -upf)](https://github.com/ease-lab/vhive/runs/2762712157?check_suite_focus=true) has failed.

2021-06-07 10:25 UTC, ustiugov reviewed
lgtm, let's wait for the manual check

2021-06-07 11:04 UTC, boramalper commented
Manual check is fine too. See https://asciinema.org/a/Y6I1HWdDLeJlvf0T191wOWxxl

2021-06-07 11:18 UTC, ustiugov approved these changes

2021-06-07 11:18 UTC, merged