Adds doc on composing functions
ease-lab/vhive pull request #277
Opened 2021-06-10 15:16 UTC by MBaczun

Documentation on bringing up workloads of composed functions.

2021-06-14 13:53 UTC, ustiugov reviewed
it's very good, thanks! let's wait for Bora to complete the eventing part.

2021-06-16 14:31 UTC, boramalper commented
@MBaczun Would you be able to review my section?

@ustiugov The file encoding is UTF-16 LE and the line endings are CRLF, FYI.

2021-06-16 15:10 UTC, ustiugov commented
I am not sure what this means... just make sure the format is meaningful on Linux/Mac. e.g., GitHub does not show the preview of that file, saying it's a binary
> 
> @ustiugov The file encoding is UTF-16 LE and the line endings are CRLF, FYI.

2021-06-16 15:53 UTC, boramalper commented
Happy to see it merged once Mike gives the green light as well.

2021-06-17 08:22 UTC, MBaczun commented
Hi, I think it looks good. I just caught one typo where you probably wanted to say "eventing" instead of serving on line 46

2021-06-17 08:22 UTC, MBaczun commented on docs/composing_functions_guide.md
> +In general, to deploy your workload with serving you will need to:
typo, should be eventing

2021-06-17 09:46 UTC, ustiugov requested changes
A good start, folks! @MBaczun can you please apply the following comments. Then, we'll do another, more detailed, review 

- [x] Rename the doc to: Adding benchmarks to vHive/Knative and stock Knative
- [ ] sign the commit
- [x] break down the text into <100 characters per line
- [x] restructure the text as following:
- a short intro, explaining that functions can be composes with synchronous calls (a caller waits for the callee) and asynchronously (no waiting). Then: Knative programming model supports Serving and Eventing that follow this model. Mention that extra k8s and Knative services (e.g., brokers) manifests are explained in the corresponding sections.
- General guidelines, incl. subsections namely docker, ... , k8s manifests (manifests should explain the difference between stock Knative and vHive manifests, i.e., talk about extra fields like guest_port and a different image variable in vHive manifests) 
- Serving (as is plus give pointers to the CI as well)
- Eventing (as is plus give pointers to the CI as well)

- [x] mention how to add tracing instrumentation (in the subsection about dockerization and gRPC)

- [x] Move Docker-compose and other less important things in a separate section below (e.g., Other recommendations)

2021-06-17 09:58 UTC, ustiugov commented
we also need to mention how to add tracing instrumentation

2021-06-17 15:16 UTC, ustiugov requested changes
Looks good but there are many minor comments.

- [x] replace "you"/your addressing with "one" or "they". choose once and be consistent
- [x] avoid "our" in a manual
- [x] remove leading whitespace
- [x] add a subsection saying that people need to add their applications to the CI, give references to the examples

as feedback, avoid using subjective adjectives like "simple", "easy", etc.

2021-06-17 15:16 UTC, ustiugov commented on docs/adding_benchmarks_guide.md
> +extended to export tracing data to a system such as [Zipkin](https://zipkin.io/), but you should
```suggestion
Tracing allows gathering timing data in your cluster. In vHive, we export tracing data to [Zipkin](https://zipkin.io/)
for visualization. To support tracing throughout functions, one should instrument their functions
with the calls to vHive's tracing [module](utils/tracing). 
One can see instrumentation in the Serving and Eventing [examples](function-images/tests) that vHive provides.
```

2021-06-17 15:16 UTC, ustiugov commented on docs/adding_benchmarks_guide.md
> +also add opentelemetry/zipkin instrumentation to your functions to fully support the system.
```suggestion
```

2021-06-17 15:16 UTC, ustiugov commented on docs/adding_benchmarks_guide.md
> + the process is very simple:
```suggestion
vHive provides a [tracing module](utils/tracing) that can be used to instrument various functions. The module relies on [Opentelemetry](https://opentelemetry.io) that is a standard propelled by the CNCF community. In future, vHive is going to provide tracing modules in a wide range of languages (external contributions are welcome).

One can enable tracing by following these steps:
```

2021-06-17 15:16 UTC, ustiugov commented on docs/adding_benchmarks_guide.md
> +our example of function composition using serving can be found
```suggestion
The serving function composition example can be found 
```

2021-06-17 15:16 UTC, ustiugov commented on docs/adding_benchmarks_guide.md
> +
remove because it's a repetition, just add give a reference to the images of the example somewhere above.

2021-06-17 15:16 UTC, ustiugov commented on docs/adding_benchmarks_guide.md
> +containers running on your system (e.g. if you work from within `kind` containers on cloudlab), or
give a reference to the dev's guide

2021-06-17 15:16 UTC, ustiugov commented on docs/adding_benchmarks_guide.md
> +Optionally, you may choose to include a docker-compose manifest which helps with testing your
```suggestion
One may include a docker-compose manifest which helps with testing 
```

2021-06-18 08:12 UTC, MBaczun commented
Using "one" instead of "you" feels very formal and authoritative to me, some sections feel outright pretentious now 😆. I prefer the casual "you" style, but I changed everything to use the indirect "one" and "they". Let me know if it's fine.

2021-06-18 08:24 UTC, ustiugov requested changes
very good, a bit more minors

2021-06-18 08:24 UTC, ustiugov commented on docs/adding_benchmarks_guide.md
> +usage of environment variables if one wants to work with vHive.
```suggestion
support.
```

2021-06-18 08:24 UTC, ustiugov commented on docs/adding_benchmarks_guide.md
> +    that is normal.
leading whitespace

2021-06-18 08:24 UTC, ustiugov commented on docs/adding_benchmarks_guide.md
> +                   grpc.WithInsecure(), grpc.WithUnaryInterceptor(otelgrpc.UnaryClientInterceptor()))
unaligned whitespace

2021-06-18 08:24 UTC, ustiugov commented on docs/adding_benchmarks_guide.md
> +One can enable tracing by following these steps:
```suggestion
One can enable tracing by following these steps (example is for Golang):
```

2021-06-18 08:34 UTC, MBaczun commented on docs/adding_benchmarks_guide.md
> +    that is normal.
I think this one is correct?

2021-06-18 08:37 UTC, ustiugov commented
Please add a link checker to our Linters workflow
https://github.com/gaurav-nelson/github-action-markdown-link-check

Links are becoming too many...

2021-06-18 08:38 UTC, ustiugov requested changes
please add the link checker and good to go

2021-06-18 10:11 UTC, ustiugov approved these changes

2021-06-18 10:11 UTC, merged