Python tracing module
ease-lab/vhive pull request #293
Opened 2021-06-22 15:09 UTC by MBaczun

wip

this will be working soon

2021-06-28 12:36 UTC, ustiugov requested changes
- [ ] move the client-server sources to function-images/tests/tracing/python
- [ ] add a CI test 9 running them with plain Python is good enough
- [ ] add a unit test for Python tracing
- [ ] make sure opentelemetry dependencies are installed properly (e.g., via the requirements.txt file)
- [ ] add a screenshot from Zipkin
- [ ] add copyrights
- [ ] remove empty files unless they are required

2021-06-28 12:36 UTC, ustiugov commented on utils/tracing/python/examples/client-server/greeter_client.py
> +            response = stub.SayHello(helloworld_pb2.HelloRequest(name=name))
simplify
```suggestion
            response = stub.SayHello(helloworld_pb2.HelloRequest(name="world"))
```

2021-06-28 12:36 UTC, ustiugov commented on utils/tracing/python/examples/client-server/requirements.txt
> +futures
you probably need to install opentelemetry as well, right?

2021-06-28 12:36 UTC, ustiugov commented on utils/tracing/python/examples/client-server/server.py
> +        return helloworld_pb2.HelloReply(message=msg)
simplify
```suggestion
        return helloworld_pb2.HelloReply(message= request.name)
```

2021-06-28 12:36 UTC, ustiugov commented on utils/tracing/python/examples/spans/spanExample.py
> +from ... import tracing
replace with a unit test

2021-06-29 15:20 UTC, ustiugov requested changes
hope this helps

- [x] rename tracing/python/client-server to  tracing/python/integ-tests/client-server
- [x] add a line to the changelog (in the UNRELEASED section)

2021-06-29 15:20 UTC, ustiugov commented on .github/workflows/python_tracing.yml
> +name: Python tracing CI
add this to the unit-test files outside of the matric though. too many workflows as of now

2021-06-29 15:20 UTC, ustiugov commented on function-images/tests/tracing/python/client-server/Dockerfile
> +
create WORKDIR, e.g., /app and copy the stuff there. don't work in the `/` folder, calls for trouble.

2021-06-29 15:20 UTC, ustiugov commented on function-images/tests/tracing/python/client-server/Makefile
> +	cd ../../../../../ && docker build --tag vhiveease/py-tracing-server:latest --target server -f ./function-images/tests/tracing/python/client-server/Dockerfile .
define an env variable and use it instead:
```
ROOT=../../../../../
```
watch the quote marks, not sure about those.

2021-06-29 15:20 UTC, ustiugov commented on function-images/tests/tracing/python/client-server/goclient/goclient.go
> +	conn, err := grpc.Dial(fmt.Sprintf("%v:%v", *address, *clientPort), grpc.WithInsecure(), grpc.WithUnaryInterceptor(otelgrpc.UnaryClientInterceptor()))
line is too long, 80-100 char max

2021-06-29 15:20 UTC, ustiugov commented on function-images/tests/tracing/python/client-server/requirements.txt
> +grpcio
fix this one as well

2021-06-29 15:34 UTC, ustiugov commented on function-images/tests/tracing/python/client-server/Dockerfile
> +#ENTRYPOINT ["/usr/local/bin/python", "/server.py"]
remove

2021-06-30 11:45 UTC, ustiugov approved these changes
double check that you get meaningful traces after all the changes. then merge it

2021-06-30 11:45 UTC, ustiugov requested changes
rebase please!

2021-06-30 11:56 UTC, MBaczun commented
Zipkin traces still all look correct 👍

2021-06-30 13:49 UTC, ustiugov approved these changes

2021-06-30 15:32 UTC, merged