Created generic coordinator for cri
ease-lab/vhive pull request #304
Opened 2021-06-25 16:08 UTC by nathanieltornow

Fixes #303 

- Created an interface "Coordinator" (in cri/coordinator/types.go), that coordinators need to implement in order to integrate with the vhive-cri. 
- Renamed and restructured firecracker-coordinator, which implements the coordinator-interface
- Changed service, so it works on the coordinator interface (takes a specific coordinator-type when creating)
- Commented out some lines on cri/container_create.go, which I think don't have an effect (besides maybe for testing). If there needed, we would have to add the function "InsertActive" to the Coordinator interface.

All tests (with `make test-cri`) are successful.

2021-06-25 16:33 UTC, ustiugov requested changes
a good start 

- [ ] add copyright notices
- [ ] other comments inline

2021-06-25 17:00 UTC, nathanieltornow commented on cri/container_create.go
> +	// }
Ok, so should the coordinator interface then also have the methods
```go
InsertActive(containerID, funcInst) error
IsActive(containerID) bool
RemoveActive(containerID) error
```
that will give the service information and control about active function instances?

2021-06-25 17:01 UTC, ustiugov commented
practical advice: avoid changing the "main" branch in your forks, keep main in sync with upstream and use per-feature branches

2021-06-25 17:02 UTC, nathanieltornow commented on cri/container_create.go
> +	guestIP, err := s.coordinator.StartSandbox(context.Background(), guestImage)
Ok, yes I'll change it back

2021-06-25 17:03 UTC, ustiugov commented on cri/container_create.go
> +	// }
yep. currently vHive assigns IPs to Firecracker MicroVMs on its own. it's probably not necessary when using stock containerd as you are going to with gVisor

2021-06-25 17:54 UTC, nathanieltornow commented
I don't understand why the vhive-cri-tests are timing out when creating a service. It is running fine on my server-instance (xl170). Is there maybe a known issue with that?

2021-06-25 18:00 UTC, ustiugov commented
> I don't understand why the vhive-cri-tests are timing out when creating a service. It is running fine on my server-instance (xl170). Is there maybe a known issue with that?

there are sporadic issues that pop up in the CI. I'll be restarting such tests

2021-06-25 18:01 UTC, ustiugov commented
please sign off your commits to fix the linter problem (git commit -s <..>)

2021-06-26 14:49 UTC, nathanieltornow commented
I added all your requested changes, and test-cri still runs through.
So if it still doesn't run through in the CI, I'll have a look at the logs of the CI-tests.

2021-06-26 17:35 UTC, ustiugov requested changes
looks good. please clean up one comment

2021-06-26 17:35 UTC, ustiugov commented on cri/coordinator/types.go
> +	// should return the GuestIp-address
wrong comment?

2021-06-26 17:38 UTC, ustiugov commented
@plamenmpetrov can you please take a look at this refactoring and let us know what you think?

2021-06-26 17:40 UTC, nathanieltornow commented on cri/coordinator/types.go
> +	// should return the GuestIp-address
Oh yes, sorry for that, removed them

2021-06-26 17:45 UTC, ustiugov commented
@nathanieltornow the PR looks good. let’s wait a bit for another approval before merging but you can go ahead with your other changes.

2021-06-26 20:46 UTC, nathanieltornow commented
Im so sorry, this was a mistake, I'm fixing it right now

2021-06-27 13:12 UTC, ustiugov approved these changes

2021-06-28 08:58 UTC, plamenmpetrov commented
Hello, thank you for your interest in the project!

### What should the interface look like?
It could be beneficial to have an interface for the coordinator. However, it could be better to go one abstraction level higher and have an interface as follows which different sandboxing coordinators can implement:
```
interface {
CreateContainer(ctx context.Context, r *criapi.CreateContainerRequest) (*criapi.CreateContainerResponse, error)
RemoveContainer(ctx context.Context, r *criapi.RemoveContainerRequest) (*criapi.RemoveContainerResponse, error)
}
```
To understand this better from my perspective: The coordinator is tightly coupled with firecracker. I am not confident to foresee how much of the coordinator interface that you propose will translate well for gVisor or other sandboxing technologies. But perhaps this is not important. What really matters is the implementation of `CreateContainer` and `RemoveContainer` (currently inside `container_create.go` and `container_remove.go`. 

With the interface I propose, `container_create.go` will be look more or less as follows:
```
func (s *Service) CreateContainer(ctx context.Context, r *criapi.CreateContainerRequest) (*criapi.CreateContainerResponse, error) {
    return s.sandboxingtechnology.CreateContainer(ctx, r)
}
```
It will be analogous for `container_remove`. Then, for each sandboxing technology we can implement `CreateContainer` and `RemoveContainer`, which may or may not need to involve a coordinator.

### How should the code be strcutured if we support multiple sandboxing technologies?
The firecracker coordinator relies on the firecracker-containerd orchestrator (`ctriface.Orchestrator`). In the same way, the gVisor coordinator will have to rely on some sort of gVisor ochestrator. If we decide to place all coordinators in the cri package, where do we implement the gVisor orchestrator? Will it be in `vhive/gvisoriface`? What about if we add additional virtualization technologies? It might make more sense to have 1 package for firecracker, 1 for gVisor, 1 for any other new supported we decide to support. All of these will have their own ctriface, own coordinator, etc. Then, in `vhive.go` you could specify whether you want to use firecracker-containerd, gVisor, or anything else.

Some more concrete comments:
1. Currently, it looks like the `cri/coordinator/gvisor/coordinator.go` file contains a dummy implementation. I see from #303 that the plan is to implement an orchestrator for gVisor as well, so could we leave the creation of this file and the gVisor package as a whole for that future PR?
2. The `cri_test.go` file is in the firecracker coordinator package. Apart from `TestMain` (which can be moved to `coordinator_test.go`, the tests in `cri_test.go` should not be specific to a particular coordinator implementation (or orchestrator implementation for that matter). Could you move it outside of the firecracker coordinator package?

2021-06-28 10:48 UTC, nathanieltornow commented
Hi @plamenmpetrov, thank you for your comments.

#### Regarding "What should the interface look like"
Yes, I think your suggestion would also be a great approach. 
The only problem I see there is that you might have to change kubernetes/knative configurations when switching sandboxing techniques. In my understanding, the current cri will create either QP-containers or VMs, depending on the call.
So the benefit of doing the abstraction at the coordinator-level would be, that the functionality of the QP-container stays the exactly same,  and on `StartSandbox()` just one sandbox (either gvisor or fc) will be created, returning an IP-address to the sandbox, that the QP uses to reach the sandbox. 

#### Regarding "How should the code be structured"
I'm open to the overall structure of the code. I think having completely separate packages for each sandboxing technique would be definitely the cleanest approach.

#### Regarding your concrete comments
Yes, I will make those changes.

2021-06-28 17:38 UTC, ustiugov commented
Thanks a lot, folks! I appreciate the discussion.

I agree with @plamenmpetrov that the interface approach is desirable. I also agree that we should move the tests to the `cri/` folder so that we can just fire the same tests with a different runtime option. 

Some clarification for gVisor integration, compared to Firecracker. We are going to follow the same dual-containerd setup, as before, with one for function instance sandboxes and one for regular containers. 

gVisor is going to use a stock containerd **with a gVisor plugin**. Hence, to support gVisor, we just need to set up an extra containerd daemon and a CRI coordinator to forward all commands from k8s to that containerd-with-the-plugin. For example, the cri module doesn't need to implement the IP addresses management. However, we would like to have a possibility to have some sandbox management inside the CRI coordinator (e.g., cgroups limits). 

@nathanieltornow could you please implement the interface-based architecture? also, could you please move the tests a level up under the `cri/` folder? it would also require adding a runtime argument for the tests to either run the Firecracker and the gVisor coordinators?

Regarding the dummy gVisor code, I would leave it as is. We are not going to merge the code into `main` before gVisor support is completely ready. Instead, we are going to push the code to a `feature/gvisor` branch (as a copy of Nathaniel's branch) and open PRs against it. I am going to give @nathanieltornow write permissions to push his branch directly into upstream. @nathanieltornow please push your current branch as a `feature/gvisor` branch to upstream.

2021-06-28 20:58 UTC, plamenmpetrov commented
@nathanieltornow Thank you for taking care of the small changes so quickly. Yes, separate packages for each runtime, e.g. firecracker-containerd, gVisor makes the most sense to me as well.

@ustiugov Thanks for clarifying. It seems altogether that the gVisor support should not present major issues.

As far as the coordinator/interface question is concerned, each runtime (firecracker-containerd, gVisor, containerd, etc.) needs to implement the CRI interface to work with Kubernetes. In vHive right now, the [`service`](https://github.com/ease-lab/vhive/blob/main/cri/service.go#L47) struct does that for firecracker-containerd. It proxies most CRI calls to stock containerd and intercepts `CreateContainer` and `RemoveContainer`. 

It is possible that for other runtimes, like gVisor, a different implementation of CRI is more suitable. For example, we might not want to make the distinction for queue-proxy and user-container. (@ustiugov , I know you said you want to do that, but I am giving an example. As a result, implementing the interface at the coordinator level might be restrictive for some other runtimes. For this reason, the right interface might be actually CRI. This will be the most liberal approach. To see this, for each runtime there will be a [service](https://github.com/ease-lab/vhive/blob/main/cri/service.go#L47) (like the one for firecracker-containerd), which will implement CRI. Then, the CRI implementation for the runtime can afford to make changes to other CRI calls, not only `CreateContainer` and `RemoveContainer`.

Let me know what you think.

2021-06-28 22:47 UTC, nathanieltornow commented
Thanks for all your comments!
@ustiugov I created the feature/gvisor branch with the current code of this PR and will make my next PRs to this branch.
I implemented an interface as suggested by @ustiugov and pushed it to [nathanieltornow/feature/gvisor](https://github.com/nathanieltornow/vhive/tree/feature/gvisor), and I think it is a clearer approach to before.
- Interface is in [cri/types.go](https://github.com/nathanieltornow/vhive/blob/feature/gvisor/cri/types.go)
- Firecracker implementation in [cri/firecracker/service.go](https://github.com/nathanieltornow/vhive/blob/feature/gvisor/cri/firecracker/service.go)

@plamenmpetrov I agree, introducing the interface at the CRI-level might be the best solution, since it introduces the most separation between unrelated components. The only concern I'm having with that solution is, that you won't be able to change between different sandboxing-techniques with setting a flag to `./vhive`, but maybe also have to change knative-settings as well.

2021-06-29 06:57 UTC, ustiugov commented
@plamenmpetrov I think that we should keep the dual-containerd architecture and build upon it. Proxying CRI requests gives us more control that might be useful in future, and running everything in gVisor might lead to problems with regular stateful services. Keeping only functions in gVisor sandboxes would be more localized and easier to maintain.

2021-06-29 08:51 UTC, ustiugov commented
please re-open this PR from feature/gvisor

2021-06-29 08:51 UTC, closed without merging

2021-06-29 11:43 UTC, plamenmpetrov commented
@ustiugov It is true that it might not work out of the box, but having the possibility to do it in the future without other changes is probably desirable. Anyways, I am not arguing strongly.

@nathanieltornow Having the interface at the CRI level will not impact `vhive/vhive.go`. Depending on the flag (fccd, gVisor, etc.), we can create the respective service, which implements CRI.