Add word_count uBenchmark
ease-lab/vhive pull request #349
Opened 2021-07-23 14:20 UTC by boramalper

Signed-off-by: Bora M. Alper <bora@boramalper.org>

2021-07-25 09:08 UTC, ustiugov requested changes

2021-07-25 09:08 UTC, ustiugov commented on function-images/tests/word_count/Dockerfile
> +FROM golang:1.16.6-buster AS builder
use the vhiveease go image instead

2021-07-25 09:08 UTC, ustiugov commented on function-images/tests/word_count/Dockerfile
> +FROM debian:buster
use scratch (at least when debugging is done)

2021-07-25 09:08 UTC, ustiugov commented on function-images/tests/word_count/word-count.yml
> +            - name: h2c
this works for HTTP/2 (gRPC) but may not work for the original HTTP

2021-07-26 14:40 UTC, boramalper commented
@ustiugov Ready

2021-07-26 14:52 UTC, ustiugov approved these changes

2021-07-26 14:52 UTC, ustiugov commented on function-images/tests/word_count/word_count.go
> +		corral.WithSplitSize(10 * 1024),
How can one configure those? Only in the code?

2021-07-26 14:53 UTC, merged