Function image for gg port. Still need working ingress. Clean merge
ease-lab/vhive pull request #372
Opened 2021-08-03 19:33 UTC by cbfariasc

Instructions to run an example from gg (using the repository at https://github.com/faromero/gg/tree/vhive_port) can be found here: https://github.com/StanfordSNR/gg#build-directions
Note: The last command (gg force) should have the parameter "--engine vhive=<ingress-url-or-ip>" once we have the public ingress properly configured.

2021-08-03 20:03 UTC, ustiugov requested changes
much better now :) 

Please apply the rest of my comments from the previous review.  Also, the gg-static binary is still committed as a binary. please fix. 

We'll give it a try soon and then we could proceed with a guidance wrt our CI integration.

2021-08-16 11:24 UTC, MBaczun commented
Encountering an issue when trying to run this on a cloudlab machine. While building gg, specifically the `make -j$(nproc)` command, I see this:
```bash
make[4]: Entering directory '/users/MBaczun/gg/src/protobufs'
  CXX      thunk.pb.o
  CXX      gg.pb.o
  CXX      meow.pb.o
In file included from meow.pb.cc:4:0:
meow.pb.h:10:10: fatal error: google/protobuf/port_def.inc: No such file or directory
 #include <google/protobuf/port_def.inc>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
Makefile:367: recipe for target 'meow.pb.o' failed
make[4]: *** [meow.pb.o] Error 1
make[4]: *** Waiting for unfinished jobs....
In file included from gg.pb.cc:4:0:
gg.pb.h:10:10: fatal error: google/protobuf/port_def.inc: No such file or directory
 #include <google/protobuf/port_def.inc>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from thunk.pb.cc:4:0:
thunk.pb.h:10:10: fatal error: google/protobuf/port_def.inc: No such file or directory
 #include <google/protobuf/port_def.inc>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```
The same error comes up when I try to set up a docker image.

### Steps to reproduce:
1. rent a cloudlab machine using the `vHive-cluster-quickstart` profile and with 1 node.
2. setup vHive side:
      a. clone `https://github.com/faromero/vhive.git`, checkout `gg_port_new`
      b. Setup vhive normally: `setup_node`, `sudo containerd`, and `create_one_node_cluster`, as described [here](https://github.com/faromero/vhive/blob/main/docs/developers_guide.md#testing-stock-knative-setup-or-images)
      c. wait for pods to become ready, then `kn service apply gg-port-0 --filename configs/knative_workloads/gg_port.yaml`
      d. Confirm that the function becomes available with `kn service list`
3. cd out of the vhive repo (`cd ..`), clone `https://github.com/faromero/gg.git` and checkout `vhive_port`.
4. Follow the gg build directions as described [here](https://github.com/StanfordSNR/gg#build-directions)
      a. If you're using the same profile as me then the machine does not have `sudo` so you might see a `sudo: command not found` message. Get sudo like this: [source](https://unix.stackexchange.com/questions/354928/bash-sudo-command-not-found)
      ```bash
      su -
      apt-get install sudo -y
      ```
      b. install dependencies:
      ```bash
      sudo apt-get install gcc-7 g++-7 protobuf-compiler libprotobuf-dev \
                     libcrypto++-dev libcap-dev \
                     libncurses5-dev libboost-dev libssl-dev autopoint help2man \
                     libhiredis-dev texinfo automake libtool pkg-config python3-boto3
      ```
      c. apply gg setup commands (please run one at a time):
      ```bash
      ./fetch-submodules.sh
      ./autogen.sh
      ./configure
      make -j$(nproc)
      ```
      upon running the make command you should encounter the error.
5. if you wish to try the setup using docker instead, follow the [gg docker instructions](https://github.com/StanfordSNR/gg#build-directions) but with a few changes:
     a. The profile does not have docker or docker-compose, you need to install them manually. I've found the [official instructions](https://docs.docker.com/engine/install/ubuntu/) don't seem to work so I used `sudo apt install docker.io`. Likewise for compose: `sudo apt install docker-compose`.
     b. Make a .env file at the root of the gg repo. You can use my .env to save having to find all the aws info (contains aws secret keys, dm me)
     c. `docker-compose build`
     d. enter the container: `docker-compose run --rm runner -c /bin/bash`
     e. run `./docker/bin/compile`, you should encounter the same error at this stage.

2021-08-16 19:31 UTC, MBaczun commented
Previous issue more or less resolved- running GG setup before vHive setup is a workaround.

2021-09-04 10:27 UTC, ustiugov requested changes
hi everyone, it seems that we are close to make gg work, which is cool! Here is the raw todo list to finish this work:

First, need to verify that gg works:
- [ ] Need to write 2 scripts for set up and run gg (and check out the right branches, etc), currently instructions are extremely convoluted. You can assume that a user should provide a file to source the environment variables from

After that:
- [ ] remove all the code from this branch that is not related to the basic gg port (e.g., invoker changes, benchmark.yaml, etc.)
- [ ] use git LFS for binaries (example is in <repo>/bin folder
- [ ] don't use a builder docker image, with slim it's enough to use a single image for everything
- [ ] rename gg_port into gg_framework
- [ ] add a readme
- [ ] merge the commits into one (the last step)

2021-09-04 20:00 UTC, ustiugov commented on configs/knative_workloads/gg_port.yaml
> +            - image: docker.io/cbfarcan/gg_port:var_workload
```suggestion
            - image: docker.io/faromero/gg_port:var_workload
```

2021-09-07 22:37 UTC, ustiugov reviewed
@shyamjesal can you please go over the readme and try to see if it is sufficient for a newcomer to follow? and also double check that "llvm" and "excamera" examples work

The code looks good, just a couple of things to complete:
- [ ] need to add copyrights
- [ ] need to decide whether we support Minio or just rely on AWS. does gg support Minio backend as of now?

2021-09-07 22:37 UTC, ustiugov commented on function-images/gg_framework/greeter_client.py
> +        minioClient = Minio("10.138.0.27:9000",
do we need the minio code? or we just keep AWS for now?

2021-09-07 22:37 UTC, ustiugov commented on function-images/gg_framework/requirements.txt
> +google
need to fix the versions of each python module to avoid incompatibility issues

2021-09-07 22:37 UTC, ustiugov commented on function-images/minio_scripts/create_object_of_size_and_store_in_bucket.sh
> +#!/bin/bash
not sure if we need the minio stuff

2021-09-08 17:46 UTC, faromero commented
Please check that the licenses are properly done; I also added the lead developer of `gg` and his respective Stanford research group.

2021-09-24 19:35 UTC, ustiugov commented
this code was moved to a separate repo: https://github.com/ease-lab/vSwarm/pull/17

2021-09-24 19:35 UTC, closed without merging