Storage module
ease-lab/vhive pull request #378
Opened 2021-08-05 15:41 UTC by MBaczun

Signed-off-by: Michal Baczun <s1743497@ed.ac.uk>

2021-08-19 14:30 UTC, ustiugov requested changes
- [x] remove the *2 suffix
- [x] fix the redis dep version
- [x] use toPickle instead of dontPickle
- [ ] add S3 unit tests to the CI (no need to test ElastiCache as of now)

2021-08-19 14:30 UTC, ustiugov commented on utils/storage/go/storage.go
> +		log.Fatalf("File transfer via ElastiCahce currently unsupported, please use []bytes: `Put(key string, payloadData []byte) string`")
```suggestion
		log.Fatalf("File transfer via ElastiCache is currently not supported, please use []bytes: `Put(key string, payloadData []byte) string`")
```

2021-08-19 14:30 UTC, ustiugov commented on utils/storage/python/requirements.txt
> +redis
fix the version

2021-08-19 14:30 UTC, ustiugov commented on utils/storage/go/storage.go
> +// Put uploads the payload to the storage service using the provided key
do we actually need this method? there is none like that in the python module

2021-08-19 14:30 UTC, ustiugov commented on utils/storage/python/storage.py
> +def put(key, obj, dontPickle = False):
I suggest using a non-neg argument to avoid confusion: `toPickle` default True

2021-08-19 15:47 UTC, MBaczun commented on utils/storage/go/storage.go
> +	AWS_S3_REGION = "us-west-1"
This happens on the line bellow. us-west-1 is just used as a default value

2021-08-20 10:23 UTC, ustiugov approved these changes
lgtm; restarting the runners now

2021-08-21 09:19 UTC, merged