Hotfix: #440. Error installing pmutools
ease-lab/vhive pull request #445
Opened 2021-12-03 22:22 UTC by dhschall

2021-12-03 22:30 UTC, ustiugov commented on scripts/install_pmutools.sh
> +sudo git clone https://github.com/ease-lab/pmu-tools -b develop /usr/local/pmu-tools2
```suggestion
sudo git clone https://github.com/ease-lab/pmu-tools -b develop /usr/local/pmu-tools
```

typo?

2021-12-03 22:31 UTC, ustiugov commented
please rebase the branch (see docs/contributing...). also, please add the description to the PR

2021-12-03 22:31 UTC, ustiugov requested changes
see above

2021-12-03 22:34 UTC, ustiugov commented
please squash the commits with `git rebase -i`

2021-12-05 13:55 UTC, ustiugov commented
Please rebase on top of main's tip

2021-12-06 07:47 UTC, dhschall commented
It seems that they fixed the upstream [repo](https://github.com/andikleen/pmu-tools/commit/8ba1376df272074a4a685f8979b31bc072d45508). We no not need to merge this PR anymore

2021-12-06 08:03 UTC, ustiugov commented
I suggest rebasing our fork to sync it up and continue using our fork, periodically syncing it up. How to do that is in contributing.md

2021-12-06 08:04 UTC, ustiugov commented
However use the main branch in our fork

2021-12-06 10:04 UTC, merged