Fixes ubuntu desktop image error of package not found
ease-lab/vhive pull request #477
Opened 2022-02-12 11:12 UTC by harshitgarg22

## Summary

Fixes #473 .

## Implementation Notes :hammer_and_pick:

* Adds universe repository in ubuntu
* Adds ca-certificates package to pull from opensuse repo

## External Dependencies :four_leaf_clover:

* N/A

## Breaking API Changes :warning:

* N/A

*Simply specify none (N/A) if not applicable.*

2022-02-12 11:15 UTC, harshitgarg22 commented
@dhuang-esl can you please confirm if this works?

2022-02-12 11:35 UTC, ustiugov requested changes
Please remove the merge commit, and rebase your branch on top of main. Please read the docs/contributing*.md for the details how to do that.

2022-02-12 11:35 UTC, ustiugov commented on scripts/setup_system.sh
> +sudo apt-get -y install curl >> /dev/null
Please combine lines 27 and 29

2022-02-12 14:05 UTC, harshitgarg22 commented
> Please remove the merge commit, and rebase your branch on top of main. Please read the docs/contributing*.md for the details how to do that.

Please check if this is fine. Thanks for the heads up.

2022-02-12 15:56 UTC, ustiugov commented
GitHub still shows 2 commits in this PR

2022-02-12 16:00 UTC, ustiugov requested changes
- [ ] Need to have 1 commit, please use 'git rebase -i' to get rid of the merge commit. 
- [ ] Move the comment as specified

2022-02-12 16:00 UTC, ustiugov commented on scripts/setup_system.sh
>  # Add skopeo sources
This comment is for the curl command, please move it down

2022-02-13 05:47 UTC, harshitgarg22 commented
> * [ ]  Need to have 1 commit, please use 'git rebase -i' to get rid of the merge commit.
> 
>     * [ ]  Move the comment as specified

The two commits were for the original change and the combining of lines. I've squashed all changes into one now. Moved the comment above the curl command.

2022-02-13 07:09 UTC, ustiugov approved these changes

2022-02-14 16:49 UTC, merged